# This is a basic workflow that is manually triggered

name: 01a Hola mundo
on:
  workflow_dispatch:
jobs:
  hola-mundo:

    runs-on: ubuntu-latest
    steps:
    - name: Hola mundo
      run: echo "Hello mundo..."
